plugins {
    id 'java'
    id 'application'
}

group = 'circulo'
version = '1.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'Main'
}

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
        }
    }
}

defaultTasks 'run'
